# config file version
apiVersion: 1

# list datasources to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5434
    database: test
    user: pgadmin
    secureJsonData:
      password: "pgpassword"
    jsonData:
      sslmode: "disable"
