# Client for viewing networking
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    run: client
spec:
  containers:
    - name: client
      image: busybox:1.34.0
      args:
        - sleep
        - "10000"
